using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Application.MongoDb.Core.Entity
{
    public interface IEntity<TPrimaryKey>
    {
        //
        // Summary:
        //     Unique identifier for this entity.
        //     standard BSonId generated by MongoDb
        [BsonId]
        TPrimaryKey Id { get; set; }
    }
}
