using System;
using Application.MongoDb.Core.Entity;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace KNN.NULLPrinter.Core.Models
{
    public class FileProcessedLog : IEntity<ObjectId>
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }

        public string remarks { get; set; }
        public string filename { get; set; }
        public string filePath { get; set; }
        public string fileArchivedPath { get; set; }
        public string action { get; set; }  //created or deleted or modified or moved to archive or whatever
          
        [BsonDateTimeOptions]
        // attribute to gain control on datetime serialization
        public DateTime timestamp { get; set; }
        
    }

    public class FileProcessedLogDto
    {
        public string Id { get; set; }

        public string remarks { get; set; }
        public string filename { get; set; }
        public string filePath { get; set; }
        public string fileArchivedPath { get; set; }
        public string action { get; set; }  //created or deleted or modified or moved to archive or whatever

        [BsonDateTimeOptions]
        // attribute to gain control on datetime serialization
        public DateTime timestamp { get; set; }

    }
}
