using Application.MongoDb.Core.Entity;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace KNN.NULLPrinter.Core.Models
{
    public class FileDirectorySetting : IEntity<ObjectId>
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }
        public string DefaultDirectoryPath { get; set; }
        public string DirectoryPath { get; set; }
        public string ArchiveDirectoryPath { get; set; }
    }
}
