using System;
using AspNetCore.MongoDb.Repository.Entity;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Application.Core.Models
{
    public class TagLocationMapping : IEntity<ObjectId>
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }

        public string tagAddress { get; set; }
        public string location { get; set; }
        
        [BsonDateTimeOptions]
        public DateTime createdAt { get; set; }
        public DateTime updatedAt { get; set; }

    }
}
